### ISSUE TITLE
pleace remove version-part from your composer.json

### ISSUE THREAD

**Issue by srhinow** [legito/api-wrapper#1]
Hallo,
i use this repo in a contao-project (cms). I can't install per composer because composer from contao has minimum-stability="beta" and your repo has explicied version: "dev-master". 

I have this forked in a privat gitlab-repo and remove this version-line.

Can you remove this version-property from composer.json?

**Comment by temistokles** [comment]
Hi, thank you for using our API and reaching back to us. We updated our API to stable version (couple more methods were added) and consider now the interface to be stable.
