### ISSUE TITLE
your explanation don't work

### ISSUE THREAD

**Issue by srhinow** [legito/api-wrapper#2]
i work with
PHP: 7.3.11 -0ubuntu0.19.10.6
Symfony: 3.4.42
Contao: 4.4.49
legito/api-wrapper 2.0.0

when i use this in my code
```
        // Create instance
        $legitoApi = new Legito($apiKey, $privateKey)->getWrapper();
```
then comes this error
```
 (1/1) FatalThrowableError
Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR)
```

when i use the getWrapper() before ->getDocumentRecord()
```
        $LegitoApi = new Legito($objType->apiKey, $objType->privateKey);
        $docList = $LegitoApi->getWrapper()->getDocumentRecord();
```
or this try for better use wrapper 
```
        $LegitoApi = new Legito($objType->apiKey, $objType->privateKey);
        $LegitoWrapper = $LegitoApi->getWrapper();
        $docList = $LegitoWrapper->getDocumentRecord();
```
then comes this error

```
ClassNotFoundException
HTTP 500 Internal Server Error
Attempted to load class "AdvancedStyle" from namespace "Legito\Api\Wrapper\Resource\V1".
Did you forget a "use" statement for another namespace?
```

**Comment by srhinow** [comment]
solution; this is the psr-4 problem. you use the false namespases:
```
namespace Legito\Api\Wrapper\Resource\V1;
```
when i rewrite all namespaces in folder 'Resource' like the class-path:
```
namespace Legito\Api\Wrapper\V1\Resource;
```
Then there will be no more errors.

**Comment by srhinow** [comment]
Apart from that, an instance is fetched in `$legitoApi` in the readme and then continued with `$this->legitoApi`

**Comment by marekskopal** [comment]
Hi Sven,

I reproduce all of your isses. 

psr-4 namespaces should be fixed, also readme file has been updated. Please upgrade to version 2.0.1
